name: CalculatorS3

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform/
      - name: Terraform apply
        run: terraform apply -auto-approve 
        continue-on-error: true
        working-directory: ./terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

  npm-install-and-build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with: 
          submodules: recursive
      - name: Install dependencies
        run: | 
          npm install
          npm run build
      - name: Cache build directory 
        uses: actions/cache@v2
        with:
          path: |
            build
          key: ${{ runner.os }}-build-${{ hashFiles('build') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Copy build artifacts to root directory
        run: |
          ls build/static/
          cp -R build/static calculator/
          cp -R node_modules calculator/ --exclude=node_modules
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
